### ISSUE TITLE
Set up a global router?

### ISSUE THREAD

**Issue by larsbrinkhoff** [bictorv/chaosnet-bridge#3]
Would it be a good idea to set up a router for a global Chaosnet?

I have aquired the domain name router.chaosnet.org.

**Comment by ams** [comment]
We should also get a DNS setup for Chaos hosts with appropriate CH records.

**Comment by bictorv** [comment]
I have this already, in a sense. I consider the cbridge at UP a central router, and have a DNS server there with CH records (including a root), since a dozen years or so. The problem might be whether the DNS server is accessible from outside. I've pushed the local (Update) admins to incorporate the Chaosnet data in their (externally accessible) DNS server, but things are slow/not prioritized.

Lars, do you also have Chaosnet.org, or "only" router.chaosnet.org? With a global chaosnet, we need a domain for the addresses (now CH-ADDR.Update.UU.SE, but CH-ADDR.Chaosnet.ORG would be better).

**Comment by larsbrinkhoff** [comment]
Only router.chaosnet.org I'm afraid.

**Comment by larsbrinkhoff** [comment]
Looking for other options.  Interestingly, chaosnet.se was registered only a month ago.

**Comment by bictorv** [comment]
ch-addr.net is now registered to me. :-)

**Comment by bictorv** [comment]
(Zone transfers work if you specify explicitly who to notify in the zone declaration, but the default notification of secondary NSs doesn't work. Anyone want to be secondary Chaos DNS?)

**Comment by bictorv** [comment]
Lars, did you already contact owners of chaos(net).{org,net,etc}? It would be nice to have a domain for "domainless" Chaosnet nodes, i.e. people without their own domain. (CH-ADDR.NET is ideal for addresses, but not as cute for hosts.) If you haven't, I might.

**Comment by larsbrinkhoff** [comment]
I contacted chaosnet.org.  It's part of sdf.org, but it's not available for us.  I reserved the name router.chaosnet.org.

Most other domain names with chaosnet or chaos seem occupied by squatters, so it's not looking good.  I think we'll have to invent something new, for example chaos-net.se.

**Comment by ams** [comment]
Maybe ambernet.org? Amber being the original file name for the Chaos paper.

**Comment by larsbrinkhoff** [comment]
CAIOSnet is an archaic synonym.

**Comment by ams** [comment]
ch-aos.net ? :-)

**Comment by bictorv** [comment]
Or some .ch domain? Ideas?

**Comment by larsbrinkhoff** [comment]
aos.ch is free. :-)

**Comment by larsbrinkhoff** [comment]
How do you make a new toplevel domain?  I'm thinking .chaosnet.

Oh, it's $200k.  Never mind.  (Who paid that to make .lol?!?)

**Comment by bictorv** [comment]
I got a response from the Chaos.net squatter^W owner: "I doubt I would let it go for less than 20K" (USD, I suppose), so that's cheaper. :-)

**Comment by bictorv** [comment]
So,
.chaosnet is way too expensive
chaos.net is (also) way too expensive, but
aosnet.ch is now mine. :-) (aos.ch wasn't actually available, although the transfer was "free")

I'll get it set up over the weekend, I hope.

**Comment by bictorv** [comment]
You can now be beta-testers of the documentation at https://www.aosnet.ch - feedback very welcome!

**Comment by larsbrinkhoff** [comment]
I think I'm already registered, right?

**Comment by bictorv** [comment]
It's a new docuwiki, so you need to get registered.

**Comment by larsbrinkhoff** [comment]
I mean this: https://www.aosnet.ch/#registering

By the way, I haven't got a response from :UP UP for some time.  I don't think I've changed anything on my end.  My ITS has been up for... "F6" days according to PEEK.

**Comment by larsbrinkhoff** [comment]
I think we should CC the LCM+L people on this too.

CC @rmaldersoniii

**Comment by bictorv** [comment]
Maybe LCM+L have a real old Chaosnet interface (or cute part of, or cable...), which a picture could be taken of, to use on www.aosnet.ch? :-)

**Comment by larsbrinkhoff** [comment]
@aap is over there now.  He sent me a picture the other day of KS10 MIT-AI's CH11 board.

That's not "real old", just "somewhat old". :-)

**Comment by bictorv** [comment]
real COMMA old. And I remember the transceiver being a bit cute, but I think ours is lost.

**Comment by ams** [comment]
Seems the page errors now. :-(

**Comment by bictorv** [comment]
Which page errors, how?

**Comment by ams** [comment]
This page is bogus:  http://opac.libraryworld.com/opac/catalog_edit.php?catalog_id=346045&from_doc=standard.php&position=1

You get a DB error.

**Comment by bictorv** [comment]
When I follow that link I see no DB error?

**Comment by larsbrinkhoff** [comment]
There should be a CH11 board near the end here  
http://aap.papnet.eu/photos/usa_2018_sorted/pdp-10/gallery.html

**Comment by ams** [comment]
I just get “Could not connect to mysql” when visiting that page.

**Comment by ams** [comment]
And the link Lars gave, doesn’t work either... it is a 402.

**Comment by aap** [comment]
Sorry, I changed the link!
http://aap.papnet.eu/pub/img/lcm/pdp-10/gallery.html

**Comment by larsbrinkhoff** [comment]
Sorry jumped the gun apparently.

**Comment by ams** [comment]
Such chaos!

**Comment by larsbrinkhoff** [comment]
Pontus says there's a CH11 board at Update, so you should be able to get all the photos you want!

**Comment by bictorv** [comment]
Cool, so maybe it isn't lost after all! I started using one of @aap s pictures on aosnet.ch, I assumed it's ok?

**Comment by bictorv** [comment]
I think this is done.

**Comment by bictorv** [comment]
I just came across Chaosnet.NET, which was available, so I got it. Now I'm uncertain whether to continue with aosnet.CH (which is fun, but sort of less obvious) or move all that to Chaosnet.NET, or find another purpose for Chaosnet.NET... Ideas/suggestions?

**Comment by larsbrinkhoff** [comment]
Aosnet.ch *is* more fun, but given the choice I'd rather go with the boring but more pedagogical Chaosnet.net.  Prospective users probably have more than enough to be confused about anyway.

**Comment by ams** [comment]
I agree.

**Comment by bictorv** [comment]
Done. @ams: aosnet.CH still doubles the info about your hosts, but they are also in ams.Chaosnet.net now.

**Comment by ams** [comment]
Cool! Should I make new certificates, etc?

**Comment by bictorv** [comment]
Ah, yes, that's a good idea (although the old will continue to work).

**Comment by bictorv** [comment]
You might also want to try the latest cbridge, which includes a somewhat working NCP, i.e. (yet another) unix sockets interface, with attached patches for supdup.c. The support for running servers is not much tested yet, but the client stuff pretty much works.

**Comment by ams** [comment]
I think you forgot to push your changes? I don't see anything new in the repository. :-(

**Comment by bictorv** [comment]
It's in the "ncp" branch, still.
